services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v6
    volumes:
      - ./centrifugo.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8010:8010
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    env_file:
      - ../.env
  web:
    build:
      context: ../
      dockerfile: prod/DjangoDockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ../.env
    environment:
      - DATABASE_HOST=db
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py fill_db 50 && gunicorn askme_fedukov.wsgi:application -c gunicorn.conf.py"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: