"""
Django settings for askme_fedukov project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / Path(".env"), override=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "1").lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS","127.0.0.1").split(",")

CSRF_TRUSTED_ORIGINS = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS","http://127.0.0.1").split(",")

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'bootstrap5',
    'livereload',
    'django_bootstrap_icons'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'livereload.middleware.LiveReloadScript',
]

ROOT_URLCONF = 'askme_fedukov.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'askme_fedukov.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

db_var_names = {
    'name': os.getenv('DATABASE_NAME_VAR', 'POSTGRES_DB'),
    'user': os.getenv('DATABASE_USERNAME_VAR', 'POSTGRES_USER'),
    'password': os.getenv('DATABASE_PASSWORD_VAR', 'POSTGRES_PASSWORD'),
    'port': os.getenv('DATABASE_PORT_VAR', 'POSTGRES_PORT'),
}

DATABASES = {
     'default': {
         'ENGINE': "django.db.backends." +  os.getenv("DATABASE_TYPE", 'postgresql'),
         'NAME': os.getenv(db_var_names['name'], 'dockerdjango'),
         'USER': os.getenv(db_var_names['user'], 'dbuser'),
         'PASSWORD': os.getenv(db_var_names['password'], 'dbpassword'),
         'HOST': os.getenv('DATABASE_HOST', '127.0.0.1'),
         'PORT': os.getenv(db_var_names['port'], 5432),
     }
 }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = 'static/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media
MEDIA_URL = '/media/'  # This is the URL for media files (user-uploaded content).
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Centrifugo settings
CENTRIFUGO_HOST = os.getenv("CENTRIFUGO_HOST", "http://localhost:8010")
CENTRIFUGO_CLIENT_TOKEN_HMAC_SECRET_KEY = os.getenv("CENTRIFUGO_CLIENT_TOKEN_HMAC_SECRET_KEY", SECRET_KEY)
CENTRIFUGO_JWT_EXPIRATION = int(os.getenv("CENTRIFUGO_JWT_EXPIRATION", 3600))
CENTRIFUGO_HTTP_API_KEY = os.getenv("CENTRIFUGO_HTTP_API_KEY", "your_api_key_here")
